Add a general `read_netcdf` function to read corrupted SOFA data
pyfar/sofar pull request #52
Opened 2023-01-20 15:20 UTC by f-brinkmann

- [x] refactor `Sofa._update_convention` to `Sofa._reset_convention`. The update functionality is already handled elsewhere
- [x] add `read_netcdf`
- [ ] rename `Sofa._protected` to `Sofa.protected` and add explaining docstring
- [ ] check where the use of `Sofa._reset_convention` is really required
- [ ] Improve error messages when reading Sofa files
- [ ] Refer to `Sofa.protected` when attempting to write read only data

2023-03-15 09:59 UTC, mberz requested changes
Looks good so far, I just don't like the name of the function ;)

2023-03-16 12:52 UTC, f-brinkmann commented on sofar/io.py
> +        A SOFA object containing the data from `filename`.
true

2023-03-16 12:55 UTC, f-brinkmann commented on sofar/io.py
> +def read_netcdf(filename):
changed it as suggested

2023-03-16 12:56 UTC, f-brinkmann commented on sofar/io.py
> +        A SOFA object containing the data from `filename`.
Yes

2023-03-16 12:59 UTC, f-brinkmann commented on sofar/io.py
> +    Read NetCDF file from disk and convert it to SOFA object.
How about this?

2023-03-30 19:12 UTC, mberz approved these changes

2023-03-31 07:35 UTC, merged