Restructure Index Page
pyfar/sofar pull request #98
Opened 2024-06-13 13:43 UTC by hoyer-a

Fabian and i talked about adding cards for the main sections on the index page instead of the toctree
 (e.g. _Getting Started, Documentation, SOFA Conventions, Contributing, Other_).

So here is a draft, still some warnings about _duplicate labels_ and _documents not included in any toctree_ due to ``include``.

2024-06-13 13:57 UTC, ahms5 reviewed
please don't delete the toc tree, otherwise the structure of the doc is not correct. you can hide the toctree by using ``:hidden:``as well and then add the cards with the links. in this way the left sidebar should still work as before.

2024-06-13 14:23 UTC, hoyer-a commented
Oops, yeah... fixing it right now. Thanks!

2024-06-13 15:10 UTC, ahms5 requested changes
thank you, looks nice!

2024-06-25 14:37 UTC, hoyer-a commented
Works well with the fa-icons.
We could move the inline css into a class in custom.css on gallery.

2024-06-27 08:04 UTC, ahms5 reviewed
Maybe can make a draft in the css before we put it in the gallery, we could temporarily put it in this pr. Also, the logos are now very small, is that intentional? 
I think we should make it properly before we merge it. based on some of my learning during the doc gallery story

2024-06-27 08:07 UTC, f-brinkmann commented
+1 for logos to be a little larger if possible

2024-06-27 09:37 UTC, ahms5 approved these changes
nice, thank you, even darkmode is working

2024-06-27 10:31 UTC, f-brinkmann submitted a review, later dismissed
Thanks a lot, really nice. I opened #102 to take track of the css style

2024-06-27 14:01 UTC, mberz requested changes
I really like the new icon design elements.

Two things though:
- I'd rename the 'documentation' to something more explicit like API reference.
- The SOFA object and sofar functions sub-pages in the TOC aren't really meaningful to people who are new and not already aware of how things are structured. So I'd prefer more descriptive names in terms of functionality.

2024-06-27 14:13 UTC, hoyer-a commented on docs/sofar.rst
> +        **Documentation**
I'm fine with API Reference instead of documentation, makes more sense to me too

2024-06-27 14:16 UTC, ahms5 commented
>     * The SOFA object and sofar functions sub-pages in the TOC aren't really meaningful to people who are new and not already aware of how things are structured. So I'd prefer more descriptive names in terms of functionality.

fair point, why do we split this anyway. we could put it into on page and add a gernal introduction instead of having two intros. in other words we merge ``sofar.functions.rst`` and ``sofar.Sofa.rst`` into ``documentation.rst``

2024-06-27 14:22 UTC, mberz commented
> > ```
> > * The SOFA object and sofar functions sub-pages in the TOC aren't really meaningful to people who are new and not already aware of how things are structured. So I'd prefer more descriptive names in terms of functionality.
> > ```
> 
> fair point, why do we split this anyway. we could put it into on page and add a gernal introduction instead of having two intros. in other words we merge `sofar.functions.rst` and `sofar.Sofa.rst` into `documentation.rst`

Sounds reasonable ;)

2024-06-27 14:22 UTC, f-brinkmann commented
I'll do a draft for that!

2024-06-28 07:54 UTC, f-brinkmann submitted a review, later dismissed

2024-06-28 08:01 UTC, ahms5 commented on docs/_static/css/fa_icon_style_draft.css
> +}
remove

2024-06-28 08:03 UTC, ahms5 requested changes
i have merged it into main in gallery, so we can use the css from the gallery now.
otherwise approved.
thank you all, now its really nice

2024-06-28 08:03 UTC, ahms5 commented on docs/conf.py
> +                  'css/fa_icon_style_draft.css'] # to be removed
```suggestion
html_css_files = ['css/custom.css']
```

2024-06-28 08:23 UTC, f-brinkmann approved these changes
Looks good to me, thanks

2024-06-28 09:26 UTC, mberz reviewed
Only typos. Otherwise approved. Looks good overall and is now more intuitive to comprehend.

2024-06-28 13:58 UTC, mberz approved these changes

2024-06-28 14:05 UTC, ahms5 approved these changes

2024-07-01 07:22 UTC, f-brinkmann approved these changes

2024-07-01 07:22 UTC, merged